training:
  batch_size: 32
  learning_rate: 2e-4
  epochs: 10
diffusion:
  timesteps: 1000
  beta_schedule: cosine
model:
  in_channels: 3
  out_channels: 3
  image_size: 32
  channels: 128
  channels_mult: [1, 2, 2, 4]
  num_res_blocks: 2
  num_heads: 4